INSERT INTO medical.roles (id, name, created_at, updated_at) VALUES
(1, 'PATIENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'DOCTOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'NURSE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO medical.appointment_type (id, name, created_at, updated_at) VALUES
(1, 'Consultation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Follow-up', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Diagnostics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Routine Check-up', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
